services:
  - type: web
    name: appclimb-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/gyms
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db.ngfuwuiewhjubridtqnt.supabase.co:5432/postgres?sslmode=require&ssl=true
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
